
DROP TABLE PLAN_T;
DROP TABLE USER_T;


CREATE TABLE USER_T(
    USER_NO    NUMBER             NOT NULL,
    USER_EMAIL VARCHAR2(100 BYTE) NOT NULL,
    USER_PW    VARCHAR2(100 BYTE) NOT NULL,
    USER_NAME  VARCHAR2(20 BYTE)  NOT NULL,
    USER_PHONE VARCHAR2(30 BYTE)  NOT NULL,
    USER_ROLE  NUMBER             NULL,
    CREATE_AT  DATE               NOT NULL,
    UPDATE_AT  DATE               NULL
);
  
CREATE TABLE PLAN_T(
    PLAN_NO	        NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	START_AT	    VARCHAR2(150)	NOT NULL,
	END_AT	        VARCHAR2(150)	NOT NULL,
	INSERT_AT	    VARCHAR2(150)	NOT NULL,
	UPDATE_AT	    VARCHAR2(150)	NULL,
	FIRST_PLAN	    VARCHAR2(100)	NOT NULL,
	FIRST_COMMENT	VARCHAR2(300)	NULL,
	SECOND_PLAN	    VARCHAR2(100)	NULL,
	SECOND_COMMENT	VARCHAR2(300)	NULL,
	THIRD_PLAN	    VARCHAR2(100)	NULL,
	THIRD_COMMENT	VARCHAR2(300)	NULL
);

 
DROP SEQUENCE USER_SEQ; 
DROP SEQUENCE PLAN_SEQ;
  
CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE PLAN_SEQ;




INSERT INTO USER_T (USER_NO, USER_EMAIL, USER_PW, USER_NAME, USER_PHONE, USER_ROLE, CREATE_AT, UPDATE_AT) VALUES(USER_SEQ.NEXTVAL, '세연', 1111, '관리자', 0, 0, TO_CHAR(SYSDATE, 'YYYY/MM/DD'), TO_CHAR(SYSDATE, 'YYYY/MM/DD'));
INSERT INTO USER_T (USER_NO, USER_EMAIL, USER_PW, USER_NAME, USER_PHONE, USER_ROLE, CREATE_AT, UPDATE_AT) VALUES(USER_SEQ.NEXTVAL, '첫회원', STANDARD_HASH('1', 'SHA256'), '회원', 01023452345, 1, TO_CHAR(SYSDATE, 'YYYY/MM/DD'), TO_CHAR(SYSDATE, 'YYYY/MM/DD'));

INSERT INTO PLAN_T (PLAN_NO, USER_NO, START_AT, END_AT, INSERT_AT, FIRST_PLAN, FIRST_COMMENT)
VALUES (1, 1, '2024-04-25 09:00:00', '2024-04-25 12:00:00', '2024-04-24 15:30:00', 'Meeting', 'Discuss project timelines');
INSERT INTO PLAN_T (PLAN_NO, USER_NO, START_AT, END_AT, INSERT_AT, FIRST_PLAN, FIRST_COMMENT, SECOND_PLAN, SECOND_COMMENT, THIRD_PLAN, THIRD_COMMENT)
VALUES (2, 1, '2024-04-26 14:00:00', '2024-04-26 17:00:00', '2024-04-24 15:45:00', 'Training', 'Training session for new employees', 'Team Meeting', 'Review project progress', 'Gym Session', 'Workout for fitness');


COMMIT;

SELECT * FROM USER_T;


 